Add EventType field
Itera/mad-learning-api pull request #15
Opened 2020-10-02 06:23 UTC by martinothamar

2020-10-02 06:52 UTC, anhtin approved these changes

2020-10-02 06:54 UTC, anhtin commented on src/MadLearning/MadLearning.API.Domain/Entities/EventModel.cs
> +            string? eventType,
Shouldn't this be typed as an enum instead of an arbitrary string?

2020-10-02 07:06 UTC, martinothamar commented on src/MadLearning/MadLearning.API.Domain/Entities/EventModel.cs
> +            string? eventType,
If we want it to be structured like tags for example then yeah, but I saw it was a string in the frontend so that's why it's string here. How do we want to use this value in the frontend, for search/filtering?

2020-10-02 08:20 UTC, LERoise requested changes
Change EventType to enum

2020-10-02 08:20 UTC, LERoise commented on src/MadLearning/MadLearning.API.Domain/Entities/EventModel.cs
> +            string? eventType,
Yes, a agree with Tin here that it should be a Enum, eventType wont change that often, and we will add tag support at a later point

2020-10-02 08:46 UTC, martinothamar commented
What values du we want here? Some suggestions here fra @martinAtItera PR: https://github.com/Itera/mad-learning-web/pull/20/files#diff-98eb49226d4d6164b8082d705d232d67R27

2020-10-02 12:56 UTC, martinothamar commented
Added the enum now. It is serialized as a number, but that is customizable

2020-10-03 12:06 UTC, anhtin commented on src/MadLearning/MadLearning.API.Domain/Entities/EventModel.cs
> +            string? eventType,
Good point, we can probably change the typing on the frontend too.

2020-10-03 12:19 UTC, anhtin commented on src/MadLearning/MadLearning.API.Domain/Entities/EventType.cs
> +    }
Nitpicking, but isn't the suffix `Event` redundant here? Like for `Workshop`, you could just name the others `SubjectMatter` and `Coding` - or `InternalCodingMeetup`. This is, of course, assuming that we consistently prefer qualified import for enums, e.g. `EventType.SubjectMatter`, over static imports, e.g. `SubjectMatterEvent`.

2020-10-04 10:28 UTC, martinothamar commented on src/MadLearning/MadLearning.API.Domain/Entities/EventType.cs
> +    }
Yeah I was thinking the same thing, but just saying "SubjectMatter" in my head as a type of event sounded wrong. If it was in Norwegian, it would be like calling it `EventType.Fag`, and all 3 are a type of "fagkveld" I guess so that's why I typed up `EventType.Fagkveld`, as it was more explicit/understandable when I read out the value/ToString value in my head. In terms of DDD you'd want the value to reflect the language of the domain, which in this case is "Kodekveld", "Fagkveld"/"Subject matter event", "Workshop" I think.

You could of course use the `using static`-directive but that's not something you enforce on a consumer of a type so I don't think we should be thinking of that in this context. I've more used that directive when there are actual naming collisions in a specific file or you're using a long name a lot of times over and over in the same file (a good example is `SyntaxFactory` from Roslyn when generating code).

2020-11-19 09:39 UTC, LERoise approved these changes

2021-01-26 07:09 UTC, martinothamar commented
Reimplemented in `update-event`

2021-01-26 07:09 UTC, closed without merging