CRUD operations for comments added, in event controller.
Itera/mad-learning-api pull request #33
Opened 2021-09-09 11:40 UTC by vegard-itera

Migration added, setting comments to empty list for existing events. RequireBehaviour added. Put Application layer dtos in Events folder, Comments dtos and commands in Comment respective folders.

Closes #27

2021-09-09 11:45 UTC, vegard-itera commented on src/MadLearning/MadLearning.API.Infrastructure/MadLearning.API.Infrastructure.csproj
> -		<PackageReference Include="MongoDB.Bson" Version="$(MongoDbVersion)" />
Oi, dette blir ikke helt som det burde? Oppgradert pga. migrations nuget pakken krevde 2.11.3
Da bør man vel droppe migrations prosjektet, og finne på noe annet? Eller skal man definere versjon

2021-09-09 11:54 UTC, LERoise requested changes
Litt flise spikking og noen spørsmål ;) 
Ellers ser det bra ut.

2021-09-09 11:54 UTC, LERoise commented on src/MadLearning/MadLearning.API.Application/Events/Commands/Comment/CommentOnEvent.cs
> +                    throw new Exception($"Person model:{personModel} may be null");
Siden null check'n nå er splittet opp så er ikke "may be null" riktig lenger, siden vi her nå er sikker på at personModel er null ;)

2021-09-09 11:54 UTC, LERoise commented on src/MadLearning/MadLearning.API.Application/Events/Commands/Comment/UpdateCommentOnEvent.cs
> +                    throw new Exception($"Person model:{personModel} may be null");
Se den andre kommentaren

2021-09-09 11:54 UTC, LERoise commented on src/MadLearning/MadLearning.API.Application/Events/Commands/Comment/UpdateCommentOnEvent.cs
> +                        throw new Exception($"Comment person model:{commentPersonModel} may be null");
Se den andre kommentaren

2021-09-09 11:54 UTC, LERoise commented on src/MadLearning/MadLearning.API.Application/Services/IDateTimeService.cs
> +namespace MadLearning.API.Application.Services
Trenger du en egen DateTimeService ? 
Hvorfor ikke bruke date time direkte ?
Hva er verdien denne servicen gir ?

2021-09-09 12:03 UTC, vegard-itera commented on src/MadLearning/MadLearning.API.Application/Services/IDateTimeService.cs
> +namespace MadLearning.API.Application.Services
Bare en vane sak; hatt tung bruk av dato felter i tidligere prosjekt og for å gjøre det mer testbart kalte vi en service. Det er vanskelig å mocke DateTime.

2021-09-10 08:20 UTC, LERoise approved these changes

2021-09-10 09:08 UTC, merged

2021-09-10 09:20 UTC, anhtin reviewed
Ay, to kommentarer her som jeg ikke rakk å sende inn 🙈

2021-09-10 09:20 UTC, anhtin commented on src/MadLearning/MadLearning.API.Application/Events/Commands/Comment/CommentOnEvent.cs
> +                }
Tror dette kan bli mer lesbart om du splitter det opp i flere funksjoner og gjør litt om på rekkefølge:
```c#
public async Task<Unit> Handle(CommentOnEvent request, CancellationToken cancellationToken)
    ...
    var commentModel = new CommentModel();
    commentModel.Body = request.CreateCommentModel.Body;
    commentModel.ReplyToCommentId = request.CreateCommentModel.ReplyToCommentId;
    commentModel.Date = DateTime.Now;
    commentModel.ChangedDate = DateTime.Now;
    commentModel.ByPerson = getPersonModel(request);
    commentModel.ReplyToPerson = await getReplyToComment(request);
    ...
}

public PersonModel getPersonModel(CommentOnEvent request) {
    return request.UserInfo.ToPersonModel()
        ?? throw new Exception("$(Person model:{personModel} is null");
}

public Async<CommentModel> getReplyToComment(CommentOnEvent request) {
    if (commentModel.ReplyToCommentId is not null)
    {
        return await this.repository
            .GetCommentOnEvent(request.Id, commentModel.ReplyToCommentId, cancellationToken)
                ?? throw new Exception($"Comment:{commentModel.ReplyToCommentId} not found");
    }
   return Task.FromResult(null);
}
```